### ISSUE TITLE
 500 Server Error

### ISSUE THREAD

**Issue by chelsey0527** [tavily-ai/tavily-python#25]
I was trying to test the searchAgent result but end up encountering 500 Server Error.
Check the Tavily API usage and it showed correct deduction after each run.
```
Traceback (most recent call last):
  File "/Users/(personal information)/backend/agents/search.py", line 24, in <module>
    results = search_agent.run(query)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/(personal information)/backend/agents/search.py", line 19, in run
    return self.search_tavily(query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/(personal information)/backend/agents/search.py", line 14, in search_tavily
    results = tavily_client.search(query=query, topic="company overview", max_results=10)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/(personal information)/venv/lib/python3.12/site-packages/tavily/tavily.py", line 48, in search
    return self._search(query, search_depth=search_depth, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/(personal information)/venv/lib/python3.12/site-packages/tavily/tavily.py", line 42, in _search
    response.raise_for_status()  # Raises a HTTPError if the HTTP request returned an unsuccessful status code
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/(personal information)/venv/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.tavily.com/search
```

**Comment by MayRamati** [comment]
Hello,

Based on your code, it seems the topic parameter is causing the problem. Currently, the Tavily Search API supports only the following values for the topic parameter: "general" and "news".
The value "company overview" is not supported, which may be why you are encountering a 500 Server Error. Please update your code as follows and re-run the query: results = tavily_client.search(query=query, topic="general", max_results=10)

For more details on the Tavily search API, please refer to our [API reference documentation](https://docs.tavily.com/docs/python-sdk/tavily-search/api-reference).
